name: setvit-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - numpy=1.24.3
  - pyyaml
  - opencv
  - matplotlib
  - scipy=1.11.3
  - wandb
  - tqdm
  - pip:
      - albumentations>=1.3.0
      - timm>=0.9.16
      - pycocotools
